version: '3.1'

services:

    database:
        image: mongo
        container_name: spaces_database
        restart: always
        volumes: 
            - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - ./database/mongo-data:/data/db
        ports:
            - 27017:27017
        environment:
            - MONGO_INITDB_DATABASE=spaces
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=secret
